# Generated by Django 4.0.4 on 2022-05-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_coursecategory_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='address',
            new_name='skills',
        ),
    ]
