# Generated by Django 4.0.4 on 2022-05-24 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_featured_image_course_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='featured_image',
            new_name='featured_img',
        ),
    ]
