# Generated by Django 4.0.4 on 2022-05-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_course_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='skills',
            new_name='bio',
        ),
    ]
