# Generated by Django 4.0.4 on 2022-05-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_student_address_remove_student_mobile_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='interested_categories',
            new_name='interests',
        ),
    ]
