# Generated by Django 4.0.4 on 2022-06-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_courserating_rating_alter_courserating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='teacher_profile_images/'),
        ),
    ]
